name: geolocator_platform_interface
description: A common platform interface for the geolocator plugin.
repository: https://github.com/baseflow/flutter-geolocator/tree/main/geolocator_platform_interface
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 4.0.7

dependencies:
  flutter:
    sdk: flutter

  plugin_platform_interface: ^2.1.4
  vector_math: ^2.1.4
  meta: ^1.8.0

dev_dependencies:
  async: ^2.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mockito: ^5.0.0-nullsafety.7

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=2.8.0"
