name: geolocator_android
description: Geolocation plugin for Flutter. This plugin provides the Android implementation for the geolocator.
repository: https://github.com/baseflow/flutter-geolocator/tree/main/geolocator_android
issue_tracker: https://github.com/baseflow/flutter-geolocator/issues?q=is%3Aissue+is%3Aopen
version: 4.1.7

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: ">=2.8.0"

flutter:
  plugin:
    implements: geolocator
    platforms:
      android:
        package: com.baseflow.geolocator
        pluginClass: GeolocatorPlugin
        dartPluginClass: GeolocatorAndroid

dependencies:
  flutter:
    sdk: flutter
  geolocator_platform_interface: ^4.0.7

dev_dependencies:
  async: ^2.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  mockito: ^5.4.0
  plugin_platform_interface: ^2.1.4
